(() => {
  const state={nodes:[],edges:[],nodeMap:new Map(),selected:null,scale:1,tx:0,ty:0,drag:null,panning:null,expanded:new Set()};
  const svg=document.querySelector('#canvas'),viewport=document.querySelector('#viewport'),nodesLayer=document.querySelector('#nodes'),edgesLayer=document.querySelector('#edges');
  const colors={domain:'#2f6f92',collection:'#6c8f48',document:'#8770ad',policy:'#c27a34',control:'#ba5252','policy-statement':'#c49a49','content-unit':'#7a8790'};
  const radius={domain:19,collection:15,document:14,policy:15,control:14,'policy-statement':10,'content-unit':9};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function post(message){if(window.chrome?.webview)window.chrome.webview.postMessage(message)}
  function ingest(payload,append=false){
    if(!append){state.nodes=[];state.edges=[];state.nodeMap.clear();state.expanded.clear()}
    for(const node of payload.nodes||[]){if(!state.nodeMap.has(node.id)){node.x=0;node.y=0;node.vx=0;node.vy=0;state.nodes.push(node);state.nodeMap.set(node.id,node)}}
    const edgeIds=new Set(state.edges.map(e=>e.id));for(const edge of payload.edges||[]){if(!edgeIds.has(edge.id)){state.edges.push(edge);edgeIds.add(edge.id)}}
    initializeLayout(append);render();if(!append){buildFilters(payload.filters?.nodeTypes||[]);updateSummary(payload.summary);document.querySelector('#scope-label').textContent=payload.scope?.domainCode||'Knowledge explorer'}
    simulate(append?60:110,()=>{fit();if(!append)selectNode(payload.focusNodeId)});
  }
  function initializeLayout(append){
    const r=svg.getBoundingClientRect(),cx=Math.max(320,r.width/2),cy=Math.max(260,r.height/2),core=state.nodes.filter(n=>n.isScopeDomain&&n.scopeDepth===1),root=state.nodes.find(n=>n.isScopeDomain&&n.scopeDepth===0);
    if(root){root.x=cx;root.y=cy;root.fx=cx;root.fy=cy}
    core.forEach((n,i)=>{const angle=-Math.PI/2+i*Math.PI*2/Math.max(1,core.length);n.x=cx+Math.cos(angle)*105;n.y=cy+Math.sin(angle)*105;n.fx=n.x;n.fy=n.y});
    const anchors=[root,...core].filter(Boolean),unplaced=state.nodes.filter(n=>!n.isScopeDomain||n.scopeDepth>1);
    unplaced.forEach((n,i)=>{const link=state.edges.find(e=>e.target===n.id&&anchors.some(a=>a.id===e.source))||state.edges.find(e=>e.source===n.id&&anchors.some(a=>a.id===e.target)),anchor=link?state.nodeMap.get(link.source===n.id?link.target:link.source):anchors[i%Math.max(1,anchors.length)],ring=210+70*(i%4),angle=(i*2.399963229728653)+(anchors.indexOf(anchor)*.7);n.x=(anchor?.x??cx)+Math.cos(angle)*ring;n.y=(anchor?.y??cy)+Math.sin(angle)*ring;n.fx=null;n.fy=null});
  }
  function render(){
    edgesLayer.innerHTML=state.edges.map(e=>`<line class="edge ${esc(e.type)}" data-id="${esc(e.id)}"></line>`).join('');
    nodesLayer.innerHTML=state.nodes.map(n=>`<g class="node density-${esc(n.density)} ${(n.gaps||[]).length?'gap':''}" data-id="${esc(n.id)}"><circle r="${radius[n.type]||10}" fill="${colors[n.type]||'#607d8b'}"></circle><text y="${(radius[n.type]||10)+15}" text-anchor="middle">${esc(short(n.label,28))}</text></g>`).join('');
    nodesLayer.querySelectorAll('.node').forEach(el=>{el.addEventListener('click',ev=>{ev.stopPropagation();selectNode(el.dataset.id)});el.addEventListener('pointerdown',ev=>{ev.stopPropagation();const n=state.nodeMap.get(el.dataset.id);state.drag={n,id:ev.pointerId};svg.setPointerCapture(ev.pointerId)})});updatePositions();applyFilters();
  }
  function short(value,max){const s=String(value||'');return s.length>max?s.slice(0,max-1)+'…':s}
  function simulate(steps,onComplete){let i=0;const tick=()=>{if(i++>=steps){onComplete?.();return}const ns=state.nodes,es=state.edges,span=Math.min(ns.length-1,48);for(let a=0;a<ns.length;a++){for(let offset=1;offset<=span;offset++){const b=(a+offset)%ns.length;if(b<=a)continue;let dx=ns[b].x-ns[a].x,dy=ns[b].y-ns[a].y,d2=Math.max(80,dx*dx+dy*dy),f=900/d2;ns[a].vx-=dx*f*.02;ns[a].vy-=dy*f*.02;ns[b].vx+=dx*f*.02;ns[b].vy+=dy*f*.02}}
      for(const e of es){const a=state.nodeMap.get(e.source),b=state.nodeMap.get(e.target);if(!a||!b)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.max(1,Math.hypot(dx,dy)),target=e.type==='semantic'?165:115,f=(d-target)*.012;a.vx+=(dx/d)*f;a.vy+=(dy/d)*f;b.vx-=(dx/d)*f;b.vy-=(dy/d)*f}
      for(const n of ns){if(n.fx!=null&&n.fy!=null){n.x=n.fx;n.y=n.fy;n.vx=n.vy=0;continue}if(state.drag?.n===n)continue;n.vx=Math.max(-18,Math.min(18,n.vx*.86));n.vy=Math.max(-18,Math.min(18,n.vy*.86));n.x+=n.vx;n.y+=n.vy}updatePositions();requestAnimationFrame(tick)};requestAnimationFrame(tick)}
  function updatePositions(){nodesLayer.querySelectorAll('.node').forEach(el=>{const n=state.nodeMap.get(el.dataset.id);if(n)el.setAttribute('transform',`translate(${n.x},${n.y})`)});edgesLayer.querySelectorAll('.edge').forEach(el=>{const e=state.edges.find(x=>x.id===el.dataset.id),a=e&&state.nodeMap.get(e.source),b=e&&state.nodeMap.get(e.target);if(a&&b){el.setAttribute('x1',a.x);el.setAttribute('y1',a.y);el.setAttribute('x2',b.x);el.setAttribute('y2',b.y)}});viewport.setAttribute('transform',`translate(${state.tx} ${state.ty}) scale(${state.scale})`)}
  function selectNode(id){const n=state.nodeMap.get(id);if(!n)return;state.selected=n;const neighbours=new Set();for(const e of state.edges){if(e.source===id)neighbours.add(e.target);if(e.target===id)neighbours.add(e.source)}nodesLayer.querySelectorAll('.node').forEach(el=>{el.classList.toggle('selected',el.dataset.id===id);el.classList.toggle('neighbour',neighbours.has(el.dataset.id))});document.querySelector('#empty-detail').hidden=true;document.querySelector('#node-detail').hidden=false;document.querySelector('#detail-type').textContent=n.type;document.querySelector('#detail-title').textContent=n.label;document.querySelector('#detail-description').textContent=n.description||'No description is available.';document.querySelector('#detail-density').textContent=`Density: ${n.density||'sparse'} · Visible relationships: ${neighbours.size}`;document.querySelector('#detail-gaps').innerHTML=(n.gaps||[]).length?n.gaps.map(g=>`<div class="gap-card"><strong>${esc(g.code)}</strong><br>${esc(g.message)}</div>`).join(''):'<div class="no-gaps">No evidence gaps detected for this node.</div>';const expand=document.querySelector('#expand');expand.hidden=!(n.type==='document'&&n.expandable);expand.textContent=state.expanded.has(n.id)?'Collapse content units':'Expand content units'}
  function buildFilters(types){document.querySelector('#type-filters').innerHTML=types.map(t=>`<label><input type="checkbox" data-type="${esc(t)}" checked> ${esc(t)}</label>`).join('');document.querySelectorAll('#type-filters input').forEach(x=>x.addEventListener('change',applyFilters))}
  function applyFilters(){const enabled=new Set([...document.querySelectorAll('#type-filters input:checked')].map(x=>x.dataset.type)),gaps=document.querySelector('#show-gaps').checked,density=document.querySelector('#show-density').checked,semantic=document.querySelector('#show-semantic').checked;nodesLayer.querySelectorAll('.node').forEach(el=>{const n=state.nodeMap.get(el.dataset.id),visible=enabled.size===0||enabled.has(n.type);el.classList.toggle('hidden',!visible);el.classList.toggle('gap',gaps&&(n.gaps||[]).length>0);el.classList.toggle('density-dense',density&&n.density==='dense');el.classList.toggle('density-sparse',density&&n.density==='sparse')});edgesLayer.querySelectorAll('.edge').forEach(el=>{const e=state.edges.find(x=>x.id===el.dataset.id),a=state.nodeMap.get(e.source),b=state.nodeMap.get(e.target),visible=(enabled.size===0||enabled.has(a.type))&&(enabled.size===0||enabled.has(b.type))&&(semantic||e.type!=='semantic');el.classList.toggle('hidden',!visible)})}
  function updateSummary(s={}){document.querySelector('#summary').innerHTML=`Nodes: <strong>${s.nodeCount??state.nodes.length}</strong><br>Relationships: <strong>${s.edgeCount??state.edges.length}</strong>${s.isTruncated?`<br><span>Showing ${s.nodeCount} of ${s.totalNodeCount}</span>`:''}`;document.querySelector('#notice').hidden=!s.isTruncated;document.querySelector('#notice').textContent=s.isTruncated?'The graph reached its safety limit. Narrow the scope to see more.':''}
  function fit(){if(!state.nodes.length)return;const xs=state.nodes.map(n=>n.x),ys=state.nodes.map(n=>n.y),minX=Math.min(...xs)-50,maxX=Math.max(...xs)+50,minY=Math.min(...ys)-50,maxY=Math.max(...ys)+50,r=svg.getBoundingClientRect();state.scale=Math.min(1.5,Math.max(.15,Math.min(r.width/(maxX-minX),r.height/(maxY-minY))));state.tx=(r.width-(minX+maxX)*state.scale)/2;state.ty=(r.height-(minY+maxY)*state.scale)/2;updatePositions()}
  document.querySelector('#find').onclick=()=>{const q=document.querySelector('#search').value.trim().toLowerCase(),n=state.nodes.find(x=>x.label?.toLowerCase().includes(q));if(n){selectNode(n.id);const r=svg.getBoundingClientRect();state.tx=r.width/2-n.x*state.scale;state.ty=r.height/2-n.y*state.scale;updatePositions()}};document.querySelector('#search').addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#find').click()});
  document.querySelector('#expand').onclick=()=>{const n=state.selected;if(!n)return;if(state.expanded.has(n.id)){const doomed=new Set(state.nodes.filter(x=>x.type==='content-unit'&&state.edges.some(e=>e.source===n.id&&e.target===x.id)).map(x=>x.id));state.nodes=state.nodes.filter(x=>!doomed.has(x.id));state.edges=state.edges.filter(e=>!doomed.has(e.source)&&!doomed.has(e.target));doomed.forEach(id=>state.nodeMap.delete(id));state.expanded.delete(n.id);render();selectNode(n.id)}else post({type:'expand-document',documentId:n.id.slice('document:'.length)})};
  document.querySelector('#fit').onclick=fit;document.querySelector('#reset').onclick=()=>{state.scale=1;state.tx=0;state.ty=0;initializeLayout(false);render();simulate(110,()=>{fit();if(state.selected)selectNode(state.selected.id)})};document.querySelector('#close').onclick=()=>post({type:'close'});['show-gaps','show-density','show-semantic'].forEach(id=>document.querySelector('#'+id).addEventListener('change',applyFilters));
  document.querySelectorAll('[data-embed-command]').forEach(button=>button.addEventListener('click',()=>{const mode=button.dataset.embedCommand;if(mode==='rebuild'&&!confirm('Rebuild every semantic embedding? Existing vectors remain available until replacements are written.'))return;document.querySelector('#embedding-status').textContent='Queueing '+mode+'…';post({type:'embedding-command',mode})}));
  svg.addEventListener('wheel',e=>{e.preventDefault();const factor=e.deltaY<0?1.12:.89,r=svg.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,old=state.scale;state.scale=Math.max(.12,Math.min(4,state.scale*factor));state.tx=x-(x-state.tx)*state.scale/old;state.ty=y-(y-state.ty)*state.scale/old;updatePositions()},{passive:false});
  svg.addEventListener('pointerdown',e=>{if(e.target===svg)state.panning={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty,id:e.pointerId}});svg.addEventListener('pointermove',e=>{if(state.drag){const r=svg.getBoundingClientRect();state.drag.n.x=(e.clientX-r.left-state.tx)/state.scale;state.drag.n.y=(e.clientY-r.top-state.ty)/state.scale;state.drag.n.vx=state.drag.n.vy=0;updatePositions()}else if(state.panning){state.tx=state.panning.tx+e.clientX-state.panning.x;state.ty=state.panning.ty+e.clientY-state.panning.y;updatePositions()}});svg.addEventListener('pointerup',()=>{state.drag=null;state.panning=null});
  window.chrome?.webview?.addEventListener('message',e=>{const m=e.data;if(m.type==='graph-loaded')ingest(m.payload);else if(m.type==='document-expanded'){ingest(m.payload,true);state.expanded.add(`document:${m.payload.documentId}`);selectNode(`document:${m.payload.documentId}`)}else if(m.type==='embedding-status'){const s=m.payload,by=s.byStatus||{};document.querySelector('#embedding-status').innerHTML=`Embedded: <strong>${by.embedded||0}</strong><br>Pending: <strong>${by.pending||0}</strong><br>Processing: <strong>${by.processing||0}</strong><br>Failed: <strong>${by.failed||0}</strong>`}else if(m.type==='error'){const notice=document.querySelector('#notice');notice.hidden=false;notice.textContent=m.message}});
  post({type:'ready'});
})();
